### ISSUE TITLE
跑不起来呀

### ISSUE THREAD

**Issue by liaohui1080** [lenxeon/gantt#1]
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! pm@0.0.1 start: `watchify -o public/javascripts/bundle.js -v -d public/javascripts/main.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the pm@0.0.1 start script 'watchify -o public/javascripts/bundle.js -v -d public/javascripts/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     watchify -o public/javascripts/bundle.js -v -d public/javascripts/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/liaohui1080/Documents/GitFile/js/gantt/npm-debug.log

**Comment by lenxeon** [comment]
nvm use v0.12.14
npm install
bin/www
npm run start
